export const galleryData = [
  {
    id: 'drinks',
    title: '酒类茶饮包装',
    moreText: '查看更多',
    items: [
      {
        id: 'zoe-ice-tea',
        title: '打奶红茶饮料',
        description: '为打奶品牌专门打造一款饮料包装',
        image: '/images/zoe-ice-tea.jpg',
        size: 'small',
      },
      {
        id: 'day-tm-2in1',
        title: 'Day_TM系列包装',
        description: '为Day_TM品牌设计一系列食品包装',
        image: '/images/day-tm-2in1.jpg',
        size: 'small',
      },
      {
        id: 'olive-tree',
        title: '橄榄树瓶子包装',
        description: '专门为橄榄树打造一款国际包装设计',
        image: '/images/olive-tree.jpg',
        hoverImage: '/images/olive-tree-hover.png',
        size: 'wideTall',
      },
      {
        id: 'snow-bottle',
        title: '精品包装',
        description: '为打奶品牌专门打造一款饮料包装',
        image: '/images/snow-bottle.jpg',
        size: 'small',
      },
      {
        id: 'tea-bottle',
        title: '优质封蜂蜜包装',
        description: 'Foodscross品牌专门为蜂蜜设计一款包装',
        image: '/images/honey-bottle.jpg',
        size: 'small',
      },
    ],
  },
  {
    id: 'snacks',
    title: '零食包装',
    moreText: '查看更多',
    items: [
      {
        id: 'cutthroat-gin',
        title: '芳香疗法包装',
        description: '插画由 mousegraphics 绘制',
        image: '/images/cutthroat-gin.jpg',
        size: 'large',
      },
      {
        id: 'zoi-icecream',
        title: 'Zoi 冰柔系列',
        description: '为Zoi品牌设计水果味一系列冰柔包装',
        image: '/images/zoi-icecream.jpg',
        size: 'small',
      },
      {
        id: 'salmon-box',
        title: 'Day_TM系列包装',
        description: '为Day_TM品牌设计一系列食品包装',
        image: '/images/salmon-box.jpg',
        size: 'small',
      },
      {
        id: 'ion-cocoa',
        title: '黑巧克力燕衣',
        description: 'ION，黑巧克力燕衣 72% 可可',
        image: '/images/ion-cocoa.jpg',
        size: 'small',
      },
      {
        id: 'asa-yellow',
        title: '三文鱼油包装',
        description: '专门为三文鱼油设计包装',
        image: '/images/asa-yellow.jpg',
        size: 'small',
      },
    ],
  },
  {
    id: 'fonts',
    title: '优质字体',
    moreText: '查看更多',
    items: [
      {
        id: 'rough-font',
        title: '拙碑体',
        description: '为打奶品牌专门打造一款饮料包装',
        image: '/images/rough-font.jpg',
        hoverImage: '/images/rough-font-hover.png',
        thumbnailFit: 'zoom',
        size: 'small',
      },
      {
        id: 'smoke-font',
        title: '烟火雅笔',
        description: '为Day_TM品牌设计一系列食品包装',
        image: '/images/smoke-font.jpg',
        thumbnailFit: 'zoom',
        size: 'small',
      },
      {
        id: 'changhai-poster',
        title: '橄榄树瓶子包装',
        description: '专门为橄榄树打造一款国际包装设计',
        image: '/images/changhai-poster.jpg',
        size: 'wideTall',
      },
      {
        id: 'escape-font',
        title: '逸尘体',
        description: 'Foodscross品牌专门为蜂蜜设计一款包装',
        image: '/images/escape-font.jpg',
        thumbnailFit: 'zoom',
        size: 'small',
      },
      {
        id: 'circle-font',
        title: '憨圆体',
        description: '为Zoi品牌设计水果味一系列冰柔包装',
        image: '/images/circle-font.jpg',
        thumbnailFit: 'zoom',
        size: 'small',
      },
    ],
  },
];
