export const galleryData = [
  {
    id: 'drinks',
    title: '酒类茶饮包装',
    moreText: '查看更多',
    items: [
     {
  id: 'zoi-ice-tea',
  title: 'ZOI ICE TEA',
  description: '桃味冰茶饮料包装设计',
  image: '/images/zoe-ice-tea.jpg',
  hoverImage: '/images/zoe-ice-tea-hover.png',
  detailImage: '/images/zoi-ice-tea-detail.png',
  size: 'small',
},
     {
  id: 'yijiazhiyan',
  title: '一家之言宠物粮包装',
  description: '四维能量系统宠物食品包装视觉设计',
  image: '/images/yijiazhiyan-cover.png',
  detailImage: '/images/yijiazhiyan-detail.png',
  size: 'small',
},
      {
        id: 'olive-tree',
        title: '橄榄树瓶子包装',
        description: '专门为橄榄树打造一款国际包装设计',
        image: '/images/olive-tree.jpg',
        hoverImage: '/images/olive-tree-hover.png',
        detailImage: '/images/my-olive-tree-detail.png',
        size: 'wideTall',
      },
      {
        id: 'snow-bottle',
        title: 'snow water包装',
        description: '为雪水饮用天然矿泉水品牌专门打造一款定制包装',
        image: '/images/snow-bottle.jpg',
        hoverImage: '/images/snow-bottle-hover.png',
        detailImage: '/images/snow-water-detail.png',
        size: 'small',
      },
      {
  id: 'greek-thyme-honey',
  title: 'Greek Thyme Honey',
  description: '极简蜂蜜品牌包装视觉设计',
  image: '/images/honey-bottle.jpg',
  hoverImage: '/images/honey-bottle-hover.png',
  detailImage: '/images/greek-thyme-honey-detail.png',
  size: 'small',
},
    ],
  },
  {
    id: 'snacks',
    title: '零食包装',
    moreText: '查看更多',
    items: [
      {
        id: 'cutthroat-gin',
        title: '芳香疗法包装',
        description: '插画由 mousegraphics 绘制',
        image: '/images/cutthroat-gin.jpg',
        hoverImage: '/images/cutthroat-gin-hover.png',
        hoverTone: 'soft',
        size: 'large',
      },
      {
        id: 'zoi-icecream',
        title: 'Zoi 冰柔系列',
        description: '为Zoi品牌设计水果味一系列冰柔包装',
        image: '/images/zoi-icecream.jpg',
        hoverImage: '/images/zoi-icecream-hover.png',
        size: 'small',
      },
      {
        id: 'salmon-box',
        title: 'Day_TM系列包装',
        description: '为Day_TM品牌设计一系列食品包装',
        image: '/images/salmon-box.jpg',
        hoverImage: '/images/salmon-box-hover.png',
        size: 'small',
      },
      {
        id: 'ion-cocoa',
        title: '黑巧克力燕衣',
        description: 'ION，黑巧克力燕衣 72% 可可',
        image: '/images/ion-cocoa.jpg',
        hoverImage: '/images/ion-cocoa-hover.png',
        size: 'small',
      },
      {
        id: 'asa-yellow',
        title: '三文鱼油包装',
        description: '专门为三文鱼油设计包装',
        image: '/images/asa-yellow.jpg',
        hoverImage: '/images/asa-yellow-hover.png',
        size: 'small',
      },
    ],
  },
  {
    id: 'fonts',
    title: '优质字体',
    moreText: '查看更多',
    items: [
      {
        id: 'rough-font',
        title: '拙碑体',
        description: '为打奶品牌专门打造一款饮料包装',
        image: '/images/rough-font.jpg',
        hoverImage: '/images/rough-font-hover.png',
        thumbnailFit: 'zoom',
        size: 'small',
      },
      {
        id: 'smoke-font',
        title: '烟火雅笔',
        description: '为Day_TM品牌设计一系列食品包装',
        image: '/images/smoke-font.jpg',
        hoverImage: '/images/circle-font-hover.png',
        thumbnailFit: 'zoom',
        size: 'small',
      },
      {
        id: 'changhai-poster',
        title: '橄榄树瓶子包装',
        description: '专门为橄榄树打造一款国际包装设计',
        image: '/images/changhai-poster.jpg',
        size: 'wideTall',
      },
      {
        id: 'escape-font',
        title: '逸尘体',
        description: 'Foodscross品牌专门为蜂蜜设计一款包装',
        image: '/images/escape-font.jpg',
        thumbnailFit: 'zoom',
        size: 'small',
      },
      {
        id: 'circle-font',
        title: '憨圆体',
        description: '为Zoi品牌设计水果味一系列冰柔包装',
        image: '/images/circle-font.jpg',
        thumbnailFit: 'zoom',
        size: 'small',
      },
    ],
  },
];
